name: Update index

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 * * * *'

permissions: {}

jobs:
  update_index:
    name: Update index
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Update index
        uses: PSModule/GitHub-Script@v1
        with:
          ClientID: ${{ secrets.SCRIBBLER_BOT_CLIENT_ID }}
          PrivateKey: ${{ secrets.SCRIBBLER_BOT_PRIVATE_KEY }}
          Script: .github/scripts/Update-Index.ps1
